const quiz=[
{
	q:'When does Exceptions in Java arises in code sequence?',
	options:['Run Time','Compilation Time','Can Occur Any Time','None of the mentioned'],
	answer:0
},
{
	q:'Which of these keywords must be used to monitor for exceptions?',
	options:['catch','try','throw','finally','throws'],
	answer:1
},
{
	q:'Which of these classes is used to define exceptions?',
	options:['Exception','Error','Throwable','System','Runnable'],
	answer:0
},
{
	q:'Which of these methods return description of an exception?',
	options:['getException()','getMessage()','obtainDescription()','obtainException()'],
	answer:1
},
{
	q:'Which of these methods is used to display stack trace?',
	options:['obtainStackTrace()','printStackTrace()','getStackTrace()','displayStackTrace()'],
	answer:1
},
{
	q:'Which of these classes is super class of Exception class?',
	options:['Throwable','System','RunTime','Class'],
	answer:0
},
{
	q:'Which of these class is related to all the exceptions that can be caught by using catch?',
	options:['Error','Exception','RuntimeExecption','All the above'],
	answer:1
},
{
	q:'Which of the following handles the exception when a catch is not used?',
	options:['finally','throw handler','default handler','Java runtime system'],
	answer:2
},
{
	q:'Which part of code gets executed whether exception is caught or not?',
	options:['try','catch','throw','finally','throws'],
	answer:3
},
{
	q:'Which of the following should be true of the object thrown by a thrown statement?',
	options:['Should be assignable to String type','Should be assignable to Exception type','Should be assignable to Throwable type','Should be assignable to Error type'],
	answer:2
},
{
	q:'At runtime, error is recoverable.',
	options:['true','false','may be','cannot predict'],
	answer:1
},
{
	q:'Which of these statements is incorrect?',
	options:['try block need not to be followed by catch block','try block can be followed by finally block instead of catch block','try can be followed by both catch and finally block','try need not to be followed by anything'],
	answer:0
},
{
	q:'Which of these methods return localized description of an exception?',
	options:['getLocalizedMessage()','getMessage()','obtainLocalizedMessage()','printLocalizedMessage()'],
	answer:0
},
{
	q:'Which of the following classes can catch all exceptions which cannot be caught?',
	options:['RuntimeException','Error','Exception','ParentException'],
	answer:0
},
{
	q:'Which of the following operators is used to generate instance of an exception which can be thrown using throw?',
	options:['thrown','alloc','malloc','new'],
	answer:0
}
]